### ISSUE TITLE
Artist/track name not show only show loading

### ISSUE THREAD

**Issue by kuyaninja** [macecchi/pebble-itunesify-remote#10] opened 2016-04-07 07:52 UTC
using pebble classic and spotify mac desktop app, the artist or track name not show on my pebble classic, spotify logo and music navigation still work good 

iTunesify Remote 1.4

**Comment by macecchi** [comment] 2016-04-08 01:05
Thanks for sharing this @kuyaninja. 
1. Can you confirm if the song details show up when using the app to control iTunes? 
2. With Spotify, does it not work only with a few songs or does it never work?

**Comment by felsmann** [comment] 2016-04-16 15:01
I can confirm with the latest server and watch app (pebble steel) track names and artist for itunes not showing up, just loading...

**Comment by felsmann** [comment] 2016-04-16 15:03
Just a thought, something could have changed on iTunes, Simon Remote is also not able to show track names

**Comment by felsmann** [comment] 2016-04-16 15:06
OK final comment, if playing content from my library it works or iTunes Radio it actually works, it seems to be only when playing from the For you section in iTunes
I hope this helps

**Comment by macecchi** [comment] 2016-04-16 15:18
Hey @felsmann! Thanks for the details :)

For some reason iTunes does not export the track info for some Apple Music songs. It appears that this only happens playing songs from public playlists or Beats 1... So I don't really know what to do (any ideas?)

I've also mentioned this [here](https://github.com/macecchi/pebble-itunesify-remote-osx/issues/4) before merging the two repos. 

I guess I could add something saying those playlists are not compatible or something like that...

**Comment by macecchi** [comment] 2016-09-07 22:24
Fixed in 00daca4679cc28097583eb4bb9451783f4a70242.

**Closed as completed by macecchi** 2016-09-07 22:24 UTC
Labels: help wanted
