### ISSUE TITLE
Still says v1.3.2 after updating

### ISSUE THREAD

**Issue by aideacomm** [macecchi/pebble-itunesify-remote#9] opened 2016-03-28 22:50 UTC
I download the most recent file and install.  The app on the pebble says that I need to update and when I check on my mac it still reads as v1.3.2

**Comment by macecchi** [comment] 2016-03-28 23:49
Hey, thanks for letting me know! :)

I believe the Mac app is indeed v1.3.2 - it has a different version number as the two apps were managed separately in the past (although I agree that it should match the Pebble app version).

I don't know why the Pebble app is telling you to update, though. I'll check it out.

Are you able to use the app anyway?

**Comment by aideacomm** [comment] 2016-03-29 12:14
Yes, after I dismiss the notification on the watch I can use the app.  However, it never displays what is playing, always says Loading…

But play/pause works and so does forward/backward.

Sincerely,

Drew Etner

**Comment by macecchi** [comment] 2016-03-30 03:06
It looks weird that you're getting this error. This error only occurs when one of the commands sent from the watch is not recognised by the Mac app and returns a 404 status code. That would/should only happen if there is a Mac/Pebble version mismatch, and I can't reproduce it here using the latest versions.

I know this is annoying, but could you try deleting the Pebble app and the Mac app, and reinstalling both of them? The latest Mac app can be found [here](https://github.com/macecchi/pebble-itunesify-remote/releases/download/v1.4/iTunesify.Remote.Mac.zip) and the Pebble app in the Pebble Appstore.

Kind regards

**Comment by macecchi** [comment] 2016-07-06 03:04
The wrong version number was fixed for the v1.5 release. 

As I do not have any more info about the other problem, I'll be closing this issue. Please test it again after v1.5 is released and, if the problem still occurs, let me know. 😉

**Closed as completed by macecchi** 2016-07-06 03:04 UTC
